import { NextPage } from 'next';
import Head from 'next/head';
import { BottomTabs } from '../components/bottomTabs/BottomTabs';
import NavigationBar from '../components/navigationBar';
import Page from '../components/Page';

const Chats: NextPage = () => (
  <Page>
    <Head>
      <title>Chat Room</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <NavigationBar title="Chat" />

    Chat

    <BottomTabs />
  </Page>
);

export default Chats;