import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Spinner, Center } from '@chakra-ui/react';
import NavigationBar from '../components/navigationBar';
import { BottomTabs } from '../components/bottomTabs/BottomTabs';

const Rooms: NextPage = () => (
  <Box>
    <Center>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar title="Rooms" />
      <Spinner mt="150" size="xl" thickness="6px" color="torch.100" />
    </Center>
    <BottomTabs />
  </Box>
);

export default Rooms;
