import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Spinner, Center } from '@chakra-ui/react';

const Room: NextPage = () => (
  <Box>
    <Center>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Spinner mt="150" size="xl" thickness="6px" color="torch.100" />
    </Center>
  </Box>
);

export default Room;
