import { NextPage } from 'next';
import Head from 'next/head';
import { BottomTabs } from '../components/bottomTabs/BottomTabs';
import NavigationBar from '../components/navigationBar';
import Page from '../components/Page';

const Settings: NextPage = () => (
  <Page>
    <Head>
      <title>Settings</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <NavigationBar title="Settings" />

    Settings
    <BottomTabs />
  </Page>
);

export default Settings;
